### ISSUE TITLE
Module breaks Episerver UI in CMS 10

### ISSUE THREAD

**Issue by marijorg** [Geta/Epi.MediaReferenceSelector#1]
CMS version:  10.10.1
Dojo debug error:

`Error: uniqName_58 template:res.dropzonedescription
    at Object.<anonymous> (widgets.js:2)
    at dojo.js:15
    at epi.js:2
    at String.replace (<anonymous>)
    at Object._1f4.substitute (epi.js:2)
    at Object._stringRepl (widgets.js:2)
    at Object.buildRendering (widgets.js:2)
    at Object.create (widgets.js:2)
    at Object.postscript (widgets.js:2)
    at new <anonymous> (dojo.js:15) "Error: uniqName_58 template:res.dropzonedescription
    at Object.<anonymous> (http://byggmakker.localtest.me/cms/Shell/10.10.6.0/ClientResources/epi/shell/widgets.js:2:67259)
    at http://byggmakker.localtest.me/cms/Shell/10.10.6.0/ClientResources/dojo/dojo.js:15:30987
    at http://byggmakker.localtest.me/cms/Shell/10.10.6.0/ClientResources/epi/epi.js:2:40412
    at String.replace (<anonymous>)
    at Object._1f4.substitute (http://byggmakker.localtest.me/cms/Shell/10.10.6.0/ClientResources/epi/epi.js:2:40226)
    at Object._stringRepl (http://byggmakker.localtest.me/cms/Shell/10.10.6.0/ClientResources/epi/shell/widgets.js:2:67114)
    at Object.buildRendering (http://byggmakker.localtest.me/cms/Shell/10.10.6.0/ClientResources/epi/shell/widgets.js:2:67657)
    at Object.create (http://byggmakker.localtest.me/cms/Shell/10.10.6.0/ClientResources/epi/shell/widgets.js:2:15513)
    at Object.postscript (http://byggmakker.localtest.me/cms/Shell/10.10.6.0/ClientResources/epi/shell/widgets.js:2:14954)
    at new <anonymous> (http://byggmakker.localtest.me/cms/Shell/10.10.6.0/ClientResources/dojo/dojo.js:15:41586)
    ----------------------------------------
    rejected at _2f8 (http://byggmakker.localtest.me/cms/Shell/10.10.6.0/ClientResources/dojo/dojo.js:15:76055)
    at _2f2 (http://byggmakker.localtest.me/cms/Shell/10.10.6.0/ClientResources/dojo/dojo.js:15:75666)
    at Promise.then._2ff.then (http://byggmakker.localtest.me/cms/Shell/10.10.6.0/ClientResources/dojo/dojo.js:15:77308)
    at when (http://byggmakker.localtest.me/cms/Shell/10.10.6.0/ClientResources/dojo/dojo.js:15:82115)
    at Object._createInternal (http://byggmakker.localtest.me/cms/Shell/10.10.6.0/ClientResources/epi/shell/widgets.js:2:221746)
    at Object.<anonymous> (http://byggmakker.localtest.me/cms/Shell/10.10.6.0/ClientResources/epi/shell/widgets.js:2:221345)
    at http://byggmakker.localtest.me/cms/Shell/10.10.6.0/ClientResources/dojo/dojo.js:15:30987
    at Object.map (http://byggmakker.localtest.me/cms/Shell/10.10.6.0/ClientResources/dojo/dojo.js:15:33829)
    at Object._createWidgets (http://byggmakker.localtest.me/cms/Shell/10.10.6.0/ClientResources/epi/shell/widgets.js:2:221275)
    at Object.<anonymous> (http://byggmakker.localtest.me/cms/Shell/10.10.6.0/ClientResources/epi/shell/widgets.js:2:220860)`

**Comment by MattisOlsson** [comment]
This is fixed in release 1.0.1. Available on Geta NuGet feed already and on it's way to Episerver's feed.
